name: Performance Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  container-test-job:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # For lower Actions usage, I just run one
        # [18, 19, 20, 21, 22, 23, 24]
        node-version: [18, 20, 22]

    container:
      image: muratkirazkaya/perf-runner:opt
      env:
        NODE_ENV: production
        NODE_VERSION: ${{ matrix.node-version }}
        PACKAGE_NAME: body-parser
        TEST_DIR: expf-tests
        PR_ID: ${{ github.event.pull_request.number || '' }}
        COMMENTTOKEN: ${{ secrets.COMMENTTOKEN }}
        REPOSITORY_OWNER: ${{ github.repository_owner }}
        REPOSITORY: ${{ github.event.repository.name }}
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)